"""Initial migration

Revision ID: 0ea045970244
Revises: 
Create Date: 2026-08-18 13:01:12.363916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ea045970244'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proposal_matches_id'), table_name='proposal_matches')
    op.drop_table('proposal_matches')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposal_matches',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('proposal_1_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('proposal_2_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('guna_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('maximum_guna', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('varna_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('vashya_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tara_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('yoni_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('graha_maitri_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('gana_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bhakoot_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('nadi_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('manglik_result', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('nadi_result', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('bhakoot_result', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('matching_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['proposal_1_id'], ['proposals.id'], name=op.f('proposal_matches_proposal_1_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposal_2_id'], ['proposals.id'], name=op.f('proposal_matches_proposal_2_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('proposal_matches_pkey'))
    )
    op.create_index(op.f('ix_proposal_matches_id'), 'proposal_matches', ['id'], unique=False)
    # ### end Alembic commands ###
