"""Add ProposalMedicalRecord

Revision ID: 1c08a871c8ed
Revises: 7105674bbe94
Create Date: 2026-08-20 16:32:57.560142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c08a871c8ed'
down_revision: Union[str, None] = '7105674bbe94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposal_medical_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=True),
    sa.Column('record_url', sa.String(), nullable=False),
    sa.Column('record_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposal_medical_records_id'), 'proposal_medical_records', ['id'], unique=False)
    op.create_index(op.f('ix_proposal_medical_records_proposal_id'), 'proposal_medical_records', ['proposal_id'], unique=False)
    op.drop_index(op.f('ix_proposal_matches_id'), table_name='proposal_matches')
    op.drop_table('proposal_matches')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposal_matches',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('proposal_1_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('proposal_2_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('guna_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('maximum_guna', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('varna_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('vashya_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tara_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('yoni_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('graha_maitri_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('gana_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bhakoot_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('nadi_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('manglik_result', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('nadi_result', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('bhakoot_result', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('matching_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['proposal_1_id'], ['proposals.id'], name=op.f('proposal_matches_proposal_1_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposal_2_id'], ['proposals.id'], name=op.f('proposal_matches_proposal_2_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('proposal_matches_pkey'))
    )
    op.create_index(op.f('ix_proposal_matches_id'), 'proposal_matches', ['id'], unique=False)
    op.drop_index(op.f('ix_proposal_medical_records_proposal_id'), table_name='proposal_medical_records')
    op.drop_index(op.f('ix_proposal_medical_records_id'), table_name='proposal_medical_records')
    op.drop_table('proposal_medical_records')
    # ### end Alembic commands ###
