"""Add is_my_profile

Revision ID: 6720dc955267
Revises: c7a2e4f1d3b5
Create Date: 2026-08-31 14:44:05.105232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6720dc955267'
down_revision: Union[str, None] = 'c7a2e4f1d3b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposal_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('data_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposal_versions_id'), 'proposal_versions', ['id'], unique=False)
    op.create_index(op.f('ix_proposal_versions_proposal_id'), 'proposal_versions', ['proposal_id'], unique=False)
    op.drop_index(op.f('ix_proposal_matches_id'), table_name='proposal_matches')
    op.drop_table('proposal_matches')
    op.add_column('proposals', sa.Column('is_my_profile', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('invitation_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile_completed', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_users_invitation_token'), 'users', ['invitation_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_invitation_token'), table_name='users')
    op.drop_column('users', 'profile_completed')
    op.drop_column('users', 'invitation_token')
    op.drop_column('proposals', 'is_my_profile')
    op.create_table('proposal_matches',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('proposal_1_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('proposal_2_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('guna_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('maximum_guna', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('varna_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('vashya_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tara_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('yoni_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('graha_maitri_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('gana_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bhakoot_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('nadi_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('manglik_result', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('nadi_result', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('bhakoot_result', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('matching_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['proposal_1_id'], ['proposals.id'], name=op.f('proposal_matches_proposal_1_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposal_2_id'], ['proposals.id'], name=op.f('proposal_matches_proposal_2_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('proposal_matches_pkey'))
    )
    op.create_index(op.f('ix_proposal_matches_id'), 'proposal_matches', ['id'], unique=False)
    op.drop_index(op.f('ix_proposal_versions_proposal_id'), table_name='proposal_versions')
    op.drop_index(op.f('ix_proposal_versions_id'), table_name='proposal_versions')
    op.drop_table('proposal_versions')
    # ### end Alembic commands ###
