"""Add proposal expenses table

Revision ID: 7105674bbe94
Revises: 35899133713c
Create Date: 2026-08-19 15:11:52.476605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7105674bbe94'
down_revision: Union[str, None] = '35899133713c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposal_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('paid_by', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposal_expenses_id'), 'proposal_expenses', ['id'], unique=False)
    op.create_index(op.f('ix_proposal_expenses_proposal_id'), 'proposal_expenses', ['proposal_id'], unique=False)
    op.drop_index(op.f('ix_proposal_matches_id'), table_name='proposal_matches')
    op.drop_table('proposal_matches')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposal_matches',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('proposal_1_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('proposal_2_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('guna_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('maximum_guna', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('varna_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('vashya_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tara_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('yoni_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('graha_maitri_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('gana_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bhakoot_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('nadi_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('manglik_result', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('nadi_result', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('bhakoot_result', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('matching_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['proposal_1_id'], ['proposals.id'], name=op.f('proposal_matches_proposal_1_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposal_2_id'], ['proposals.id'], name=op.f('proposal_matches_proposal_2_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('proposal_matches_pkey'))
    )
    op.create_index(op.f('ix_proposal_matches_id'), 'proposal_matches', ['id'], unique=False)
    op.drop_index(op.f('ix_proposal_expenses_proposal_id'), table_name='proposal_expenses')
    op.drop_index(op.f('ix_proposal_expenses_id'), table_name='proposal_expenses')
    op.drop_table('proposal_expenses')
    # ### end Alembic commands ###
