"""Add AI models

Revision ID: a98dda95f9e4
Revises: 1c08a871c8ed
Create Date: 2026-08-20 16:46:17.772885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a98dda95f9e4'
down_revision: Union[str, None] = '1c08a871c8ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    import pgvector
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.create_table('family_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('requirement', sa.String(), nullable=False),
    sa.Column('level', sa.Enum('MUST_HAVE', 'PREFERRED', 'FLEXIBLE', name='preferencelevel'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_preferences_id'), 'family_preferences', ['id'], unique=False)
    op.create_table('semantic_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=4096), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semantic_embeddings_id'), 'semantic_embeddings', ['id'], unique=False)
    op.create_table('proposal_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('field_value', sa.String(), nullable=True),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('verification_status', sa.Enum('SELF_REPORTED', 'DOCUMENT_PROVIDED', 'USER_CONFIRMED', 'VERIFIED', 'CONFLICTING', 'UNKNOWN', name='verificationstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['proposal_medical_records.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposal_fields_field_name'), 'proposal_fields', ['field_name'], unique=False)
    op.create_index(op.f('ix_proposal_fields_id'), 'proposal_fields', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proposal_fields_id'), table_name='proposal_fields')
    op.drop_index(op.f('ix_proposal_fields_field_name'), table_name='proposal_fields')
    op.drop_table('proposal_fields')
    op.drop_index(op.f('ix_semantic_embeddings_id'), table_name='semantic_embeddings')
    op.drop_table('semantic_embeddings')
    op.execute('DROP EXTENSION IF EXISTS vector')
    op.drop_index(op.f('ix_family_preferences_id'), table_name='family_preferences')
    op.drop_table('family_preferences')
    # ### end Alembic commands ###
