"""Add ProposalAnalysisRecord

Revision ID: e01352f73292
Revises: a98dda95f9e4
Create Date: 2026-08-20 12:06:43.710043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e01352f73292'
down_revision: Union[str, None] = 'a98dda95f9e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposal_ai_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('analysis_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proposal_id')
    )
    op.create_index(op.f('ix_proposal_ai_analysis_id'), 'proposal_ai_analysis', ['id'], unique=False)
    op.drop_index(op.f('ix_proposal_matches_id'), table_name='proposal_matches')
    op.drop_table('proposal_matches')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposal_matches',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('proposal_1_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('proposal_2_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('guna_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('maximum_guna', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('varna_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('vashya_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tara_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('yoni_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('graha_maitri_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('gana_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bhakoot_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('nadi_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('manglik_result', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('nadi_result', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('bhakoot_result', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('matching_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['proposal_1_id'], ['proposals.id'], name=op.f('proposal_matches_proposal_1_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposal_2_id'], ['proposals.id'], name=op.f('proposal_matches_proposal_2_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('proposal_matches_pkey'))
    )
    op.create_index(op.f('ix_proposal_matches_id'), 'proposal_matches', ['id'], unique=False)
    op.drop_index(op.f('ix_proposal_ai_analysis_id'), table_name='proposal_ai_analysis')
    op.drop_table('proposal_ai_analysis')
    # ### end Alembic commands ###
